version: '3.1'

services:
  stats-server:
    build: ./stat/stat-server
    image: stat_service_image
    container_name: stat-server
    depends_on:
      - stat-db
    ports:
      - "9090:9090"
    environment:
      - STATS_DRIVER=org.postgresql.Driver
      - STATS_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/ewm-stat
      - STATS_DB=ewm-stat
      - STATS_DB_USER=sa
      - STATS_DB_PASSWORD=password
      - PORT=9090

  stat-db:
    image: postgres:14-alpine
    container_name: stat_db
    volumes:
      - stats-data:/ann/lib/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./main-service
    image: ewm_service_image
    container_name: ewm_service
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - EWM_DRIVER=org.postgresql.Driver
      - EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - EWM_DB=ewm-main
      - EWM_DB_USER=sa
      - EWM_DB_PASSWORD=password
      - PORT=8080
      - STAT_SERVER_URL=http://stat-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    volumes:
      - ewm-data:/ann/lib/postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

volumes:
  stats-data:
  ewm-data: